default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 35432
  host: <%= ENV.fetch("DB_HOST") { "172.17.0.1" } %>
  username: postgres
  password: secretpassword

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test
